<?php

namespace Drupal\mediateca\Controller;
use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

class MediatecaController extends ControllerBase{

    public static function create(ContainerInterface $container)
    {
        return parent::create($container); // TODO: Change the autogenerated stub
    }

    public function content(){

        $messenger = \Drupal::messenger();

        $messenger->addMessage('Hola Mundo');
        $output = [];
        $output['primero'] = [
            '#markup' => '<h1>Este es el primer parrafo</h1>',
        ];
        return $output;
    }
}